# Generated by Django 3.1.5 on 2021-02-03 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20210201_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_teacher',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
