# Generated by Django 3.1.5 on 2021-02-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_kategori',
        ),
        migrations.AddField(
            model_name='question',
            name='q_kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.question_kategori'),
        ),
    ]
