# Generated by Django 3.1.5 on 2021-02-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='materi',
        ),
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
