# Generated by Django 3.1.5 on 2021-02-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20210203_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
