# Generated by Django 3.1.5 on 2021-02-08 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20210208_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.assignment'),
        ),
    ]
