# Generated by Django 3.1.5 on 2021-02-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20210209_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='assignment',
        ),
        migrations.AlterField(
            model_name='question',
            name='q_kategori',
            field=models.ForeignKey(limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.question_kategori'),
        ),
    ]
