# Generated by Django 3.1.5 on 2021-02-04 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_assignment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMateri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materi', models.TextField(null=True)),
                ('gambar', models.ManyToManyField(to='learning.ImageMateri')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='materi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.materi'),
        ),
    ]
