# Generated by Django 3.1.5 on 2021-02-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_question_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='img',
        ),
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ManyToManyField(to='learning.ImageMateri'),
        ),
    ]
