# Generated by Django 3.1.5 on 2021-02-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20210209_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('1', 'MUDAH'), ('2', 'SEDANG'), ('3', 'SULIT')], max_length=2, null=True),
        ),
    ]
