# Generated by Django 3.1.5 on 2021-02-04 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20210204_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='assignment',
        ),
        migrations.AddField(
            model_name='materi',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.assignment'),
        ),
    ]
