# Generated by Django 3.1.5 on 2021-02-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_question_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materi',
            name='assignment',
        ),
    ]
