# Generated by Django 3.1.5 on 2021-02-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20210204_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
