# Generated by Django 3.1.5 on 2021-02-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_materi_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choiches',
            new_name='choices',
        ),
    ]
