# Generated by Django 3.1.5 on 2021-02-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_materi_soal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_kategori',
            field=models.ForeignKey(limit_choices_to={'parent': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.question_kategori'),
        ),
    ]
